### ISSUE TITLE
Adding a location with delays slightly shorter than block time causes some calculations to return NaN

### ISSUE THREAD

**Issue by purrgrammer** [LarryRuane/minesim#3]
First of all thanks for the project, I'm learning a lot by playing with it.

When trying to set up remote locations for mining I ran into an issue though, I've added Moon mining to the default config. `moon` is connected to both gateways by a delay that is slightly shorter than block time:

```
china-asic     500    china-gateway 0.5   china-gpu  0.2
china-gpu       80    china-gateway 0.5   china-asic 0.2
portable        60    china-gateway 0.5
china-gateway   20    china-asic 0.5      china-gpu  0.5    iceland-gw 12   portable 0.5

iceland-gw     500    china-gateway 15    iceland2 0.5
iceland2       600    iceland-gw 0.5

moon           100    iceland-gw 500      china-gateway 500
```

When I run the simulation with the aforementioned configuration some percentages and numbers appear as `NaN`s:

```
seed-arg                          0
block-interval-arg              600
stopheight-arg              1000000
total-hashrate-arg             1860
mined-blocks                      0
total-simtime                 0.000
ave-block-time                  NaN
stale-blocks                      0
stale-rate                      NaN%
max-reorg-depth                   3
miner china-asic     hashrate-arg    500  26.88% blocks    NaN% stale-rate 100.00%
miner china-gpu      hashrate-arg     80   4.30% blocks    NaN% stale-rate 100.00%
miner portable       hashrate-arg     60   3.23% blocks    NaN% stale-rate 100.00%
miner china-gateway  hashrate-arg     20   1.08% blocks    NaN% stale-rate 100.00%
miner iceland-gw     hashrate-arg    500  26.88% blocks    NaN% stale-rate 100.00%
miner iceland2       hashrate-arg    600  32.26% blocks    NaN% stale-rate 100.00%
miner moon           hashrate-arg    100   5.38% blocks    NaN% stale-rate 100.00%
```

Am I doing something wrong? Thanks in advance.

**Comment by LarryRuane** [comment]
I'm glad it's helpful, thanks for this report! The problem is that `moon` has only outbound connections, no inbound ones -- no other miners list `moon` in their outbound connection lists.

This is documented in the in the _Configuration file_ section of the README:

> Each peer must have at least one inbound connection (another peer listing a connection to it), otherwise it won't receive any blocks and will mine on its own chain for the entire run. This behaviour will manifest itself by returning NaN for the "blocks" and "stale" fields in the results table.

Maybe this should be documented more clearly, so just to elaborate here, the simulator only gives credit to a miner for winning a block when it's certain that the block is _permanently_ part of the best chain. This means there is no branch point _earlier_ than this block (that is still being mined upon). In this case, miner-A is given credit for block 20 and miner-B for 21, but neither has yet earned credit for blocks 22 and 23:
```
                                     +-----------+    +-----------+
                                     |22         |    |23         |
                                     |           |    |           |
                                     |  miner-A  | <--+  miner-A  |
   +-----------+    +-----------+    |           |    |           |
   |20         |    |21         | <--+           |    |           |
   |           |    |           |    +-----------+    +-----------+
<--+  miner-A  | <--+  miner-B  |
   |           |    |           |    +-----------+    +-----------+
   |           |    |           | <--+22         |    |23         |
   +-----------+    +-----------+    |           |    |           |
                                     |  miner-B  | <--+  miner-B  |
                                     |           |    |           |
                                     |           |    |           |
                                     +-----------+    +-----------+
```
In your configuration, the situation is like this:
```
                 +-----------+    +-----------+    +-----------+    +-----------+
                 |1          |    |2          |    |3          |    |4          |
                 |           |    |           |    |           |    |           |
                 |  others   | <--+  others   | <--+  others   | <--+  others   | ...
+-----------+    |           |    |           |    |           |    |           |
|0          | <--+           |    |           |    |           |    |           |
|           |    +-----------+    +-----------+    +-----------+    +-----------+
|  genesis  |
|           |    +-----------+    +-----------+
|           | <--+1          |    |2          |
+-----------+    |           |    |           |
                 |  moon     | <--+  moon     | ...
                 |           |    |           |
                 |           |    |           |
                 +-----------+    +-----------+
```
Even though `moon` is sending its blocks to the gateways, they ignore them because they already know about a longer (more work) chain. If you change `moon`'s hash rate to be greater than the sum of the other miners (for example, 1800 gives it slightly over 50%), then they should switch to `moon`'s chain, and you won't get these `NaN` results.

You could argue this is a bug in the simulator; probably what it should do is, when the simulation ends, give credit for the longest chain at that moment, since in real life, that chain probably would become the best chain. Feel free to submit a PR if you'd like implement this, but that's okay if not; I can look into it when I have some time.

One detail about the simulator implementation: In the first picture above, the simulator can forget about the blocks from genesis until block 20, freeing up that memory (see the `CleanBlocks()` function). In the second picture, no blocks can ever be freed, so the simulator memory usage will grow unbounded.

**Comment by purrgrammer** [comment]
Thanks for the clarification, I wrongly assumed outbound connections relayed blocks in both directions. Should have paid more attention when reading the README 😅 I'm not very familiar with Go but perhaps a warning message could be added when one miner is "partitioned" from the network this way. In any case the simulator is very useful so thanks again!
